/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.PlayListController;

import java.util.concurrent.TimeUnit;
import javafx.beans.value.ChangeListener;
import javafx.beans.value.ObservableValue;
import javafx.util.Duration;


/**
 *
 * @author mateu
 */
public class MenuView extends javax.swing.JFrame {

    /**
     * Creates new form MenuView
     */
    public static PlayListController playListController;
    public static int ButtonEffectIndex;
    
    public MenuView() {
        initComponents();
        InitPlayList initPlayList  = new InitPlayList();
        this.MidPane.add(initPlayList);
        initPlayList.setVisible(true);
        playListController = new PlayListController();
        MenuView.ButtonEffectIndex = 0;
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        previousMusicButton = new javax.swing.JButton();
        NextMusicButton = new javax.swing.JButton();
        CadastroButton = new javax.swing.JButton();
        LoginButton = new javax.swing.JButton();
        MidPane = new javax.swing.JDesktopPane();
        Duration = new javax.swing.JLabel();
        Duration1 = new javax.swing.JLabel();
        Duration2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        nomeMusica = new javax.swing.JLabel();
        playButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        sliderMusic = new javax.swing.JSlider();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        AbrirButton = new javax.swing.JMenuItem();
        FecharButton = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        previousMusicButton.setText("<");
        previousMusicButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousMusicButtonActionPerformed(evt);
            }
        });

        NextMusicButton.setText(">");
        NextMusicButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextMusicButtonActionPerformed(evt);
            }
        });

        CadastroButton.setText("Cadastro");
        CadastroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroButtonActionPerformed(evt);
            }
        });

        LoginButton.setText("Login");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        MidPane.setLayout(new javax.swing.OverlayLayout(MidPane));

        Duration.setText("/");

        Duration1.setText("00:00");

        Duration2.setText("00:00");

        jLabel1.setText("Tocando Agora:");

        nomeMusica.setText("Nenhuma Musica");

        playButton.setText("Play");
        playButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Stop");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        sliderMusic.setValue(0);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Arquivo");
        fileMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileMenuActionPerformed(evt);
            }
        });

        AbrirButton.setMnemonic('o');
        AbrirButton.setText("Abrir");
        fileMenu.add(AbrirButton);

        FecharButton.setMnemonic('x');
        FecharButton.setText("Fechar");
        FecharButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FecharButtonActionPerformed(evt);
            }
        });
        fileMenu.add(FecharButton);

        menuBar.add(fileMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MidPane)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(previousMusicButton)
                                    .addGap(61, 61, 61)
                                    .addComponent(playButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton1)
                                    .addGap(83, 83, 83)
                                    .addComponent(NextMusicButton))
                                .addComponent(sliderMusic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Duration1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Duration)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Duration2))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(nomeMusica)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(CadastroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CadastroButton)
                    .addComponent(LoginButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MidPane, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeMusica))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Duration)
                                .addComponent(Duration2))
                            .addComponent(Duration1))
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sliderMusic, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(NextMusicButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(previousMusicButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(playButton)
                            .addComponent(jButton1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FecharButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FecharButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_FecharButtonActionPerformed

    private void fileMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileMenuActionPerformed

    }//GEN-LAST:event_fileMenuActionPerformed

    private void CadastroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroButtonActionPerformed
        CadastroView frame = new CadastroView();
        frame.setVisible(true);
    }//GEN-LAST:event_CadastroButtonActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        LoginView loginView  = new LoginView();
        this.MidPane.add(loginView);
        loginView.setVisible(true);
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void NextMusicButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextMusicButtonActionPerformed
        MenuView.playListController.getMusic().stop();
        if(MenuView.playListController.getIndex() == MenuView.playListController.getTotalNumber() - 1){
           MenuView.playListController.setIndexMusicSelected(0);
           
       }else{
           MenuView.playListController.setIndexMusicSelected(MenuView.playListController.getIndex()+1);
       }
       MenuView.playListController.getMusic().play();
       this.nomeMusica.setText(MenuView.playListController.getMusic().getName());
       Duration totalTime = MenuView.playListController.getMusic().player.getMedia().getDuration();
       this.Listenings(totalTime);
    }//GEN-LAST:event_NextMusicButtonActionPerformed

    private void previousMusicButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousMusicButtonActionPerformed
        MenuView.playListController.getMusic().stop();
        if(MenuView.playListController.getIndex() == 0){
           MenuView.playListController.setIndexMusicSelected(MenuView.playListController.getTotalNumber() - 1);
       }else{
           MenuView.playListController.setIndexMusicSelected(MenuView.playListController.getIndex()-1);
       }
        MenuView.playListController.getMusic().play();
       this.nomeMusica.setText(MenuView.playListController.getMusic().getName());
        Duration totalTime = MenuView.playListController.getMusic().player.getMedia().getDuration();
        this.Listenings(totalTime);
    }//GEN-LAST:event_previousMusicButtonActionPerformed

    private void playButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playButtonActionPerformed
        if(MenuView.ButtonEffectIndex == 0){
            this.playButton.setText("Pause");
            MenuView.playListController.getMusic().play();
            this.nomeMusica.setText(MenuView.playListController.getMusic().getName());  
            
            
            Duration totalTime = MenuView.playListController.getMusic().player.getMedia().getDuration();
            this.Listenings(totalTime);
            
            MenuView.ButtonEffectIndex = 1;
        }else{
            this.playButton.setText("Play");
            MenuView.playListController.getMusic().pause();
            MenuView.ButtonEffectIndex = 0;
        }
    }//GEN-LAST:event_playButtonActionPerformed
    public void Listenings(Duration TotalTime){
        String totalTimeString = String.format("%02d:%02d", 
                TimeUnit.MILLISECONDS.toMinutes((long) TotalTime.toMillis()),
                TimeUnit.MILLISECONDS.toSeconds((long) TotalTime.toMillis()) -
                TimeUnit.MINUTES.toSeconds(TimeUnit.MILLISECONDS.toMinutes((long) TotalTime.toMillis())) 
        );
        Duration2.setText(totalTimeString);
            
        sliderMusic.addChangeListener((ov) -> {
            if (null != MenuView.playListController.getMusic().player){
                //MenuView.playListController.getMusic().player.seek(TotalTime.multiply(sliderMusic.getValue() / 100.0));
            }else{
                sliderMusic.setValue(0);
            }
        });
        MenuView.playListController.getMusic().player.currentTimeProperty().addListener(new ChangeListener<Duration>() {
            @Override
            public void changed(ObservableValue<? extends Duration> observable, Duration oldValue, Duration newValue) {
                String TempoAgoraLabel = String.format(
                        "%02d:%02d",
                        TimeUnit.MILLISECONDS.toMinutes((long) newValue.toMillis()),
                        TimeUnit.MILLISECONDS.toSeconds((long) newValue.toMillis()) -
                        TimeUnit.MINUTES.toSeconds(TimeUnit.MILLISECONDS.toMinutes((long) newValue.toMillis())) 
                );
                //System.out.println((int) (newValue.divide(TotalTime.toMillis()).toMillis() * 100));
                Duration1.setText(TempoAgoraLabel);
                
                sliderMusic.setValue((int) (newValue.divide(TotalTime.toMillis()).toMillis() * 100));
               
            }
        });
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.playButton.setText("Play");
        MenuView.ButtonEffectIndex = 0;
        MenuView.playListController.getMusic().stop();;
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AbrirButton;
    private javax.swing.JButton CadastroButton;
    private javax.swing.JLabel Duration;
    private javax.swing.JLabel Duration1;
    private javax.swing.JLabel Duration2;
    private javax.swing.JMenuItem FecharButton;
    private javax.swing.JButton LoginButton;
    private javax.swing.JDesktopPane MidPane;
    private javax.swing.JButton NextMusicButton;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JLabel nomeMusica;
    private javax.swing.JButton playButton;
    private javax.swing.JButton previousMusicButton;
    private javax.swing.JSlider sliderMusic;
    // End of variables declaration//GEN-END:variables

}
